# PiWD - PS4

Cel zajęć: Praca z datami, przekształcanie zbioru danych przez wydobycie interesujących informacji z szeregów czasowych

Do demonstracji wykorzystamy zbiór danych _kalimati_tarkari_ zamieszczony na CEZ. Pliki danych muszą być umieszczone w tym samym folderze co notatnik.

Zadania samodzielne będziecie Państwo wykonywać na tym samym zbiorze danych. W dalszej cześci notatnika będzie on objaśniony.

-----

Często mamy dostęp do danych, ale dopiero wydobycie ciekawych informacji stanowi o ich wartości.

## Przykłady

In [1]:
import pandas as pd
df = pd.read_csv("kalimati_tarkari_dataset.csv", parse_dates=[2]) # w kolumnie o indeksie 2 jest data
df.head()

   SN            Commodity       Date Unit  Minimum  Maximum  Average
0   0   Tomato Big(Nepali) 2013-06-16   Kg     35.0     40.0     37.5
1   1  Tomato Small(Local) 2013-06-16   Kg     26.0     32.0     29.0
2   2           Potato Red 2013-06-16   Kg     20.0     21.0     20.5
3   3         Potato White 2013-06-16   Kg     15.0     16.0     15.5
4   4   Onion Dry (Indian) 2013-06-16   Kg     28.0     30.0     29.0

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 197161 entries, 0 to 197160
Data columns (total 7 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   SN         197161 non-null  int64
 1   Commodity  197161 non-null  str
 2   Date       197161 non-null  datetime64[us]
 3   Unit       197161 non-null  str
 4   Minimum    197161 non-null  float64
 5   Maximum    197161 non-null  float64
 6   Average    197161 non-null  float64
dtypes: datetime64[us](1), float64(3), int64(1), str(2)
memory usage: 10.5 MB

Zbiór danych zawiera 
 - indeks, 
 - nazwę notowanego dobra, 
 - data notowania ceny, 
 - jednostkę miary za którą jest podana cena, 
 - minimalna cena danego dnia,
 - maksymalna cena danego dnia,
 - średnia z minimalnej i maksymalnej ceny danego dnia.

In [3]:
print(pd.Series(df["Commodity"].unique()).str.cat(sep=", "))

Tomato Big(Nepali), Tomato Small(Local), Potato Red, Potato White, Onion Dry (Indian), Carrot(Local), Cabbage(Local), Cauli Local, Raddish Red, Raddish White(Local), Brinjal Long, Brinjal Round, Cow pea(Long), Green Peas, French Bean(Local), Soyabean Green, Bitter Gourd, Bottle Gourd, Pointed Gourd(Local), Snake Gourd, Smooth Gourd, Sponge Gourd, Pumpkin, Squash(Long), Turnip, Okara, Christophine, Brd Leaf Mustard, Spinach Leaf, Cress Leaf, Mustard Leaf, Fenugreek Leaf, Onion Green, Mushroom(Kanya), Asparagus, Neuro, Brocauli, Sugarbeet, Drumstick, Red Cabbbage, Lettuce, Celery, Parseley, Fennel Leaf, Mint, Turnip A, Tamarind, Bamboo Shoot, Tofu, Gundruk, Apple(Jholey), Banana, Lime, Pomegranate, Mango(Maldah), Grapes(Green), Water Melon(Green), Sweet Orange, Pineapple, Cucumber(Local), Jack Fruit, Papaya(Nepali), Sugarcane, Ginger, Chilli Dry, Chilli Green, Capsicum, Garlic Green, Coriander Green, Garlic Dry Chinese, Garlic Dry Nepali, Clive Dry, Clive Green, Fish Fresh, Arum, Maize, Sweet Lime, Guava, Mombin, Barela, Lemon, Sword Bean, Orange(Nepali), Bakula, Yam, Sweet Potato, Mandarin, Knolkhol, Cauli Terai, Kinnow, Strawberry, Bauhania flower, Pear(Local), Litchi(Local), Musk Melon, Tomato Small(Tunnel), Potato Red(Indian), Mushroom(Button), Apple(Fuji), Cucumber(Hybrid), Chilli Green(Bullet), Chilli Green(Machhe), Chilli Green(Akbare), Fish Fresh(Rahu), Fish Fresh(Bachuwa), Fish Fresh(Chhadi), Fish Fresh(Mungari), Raddish White(Hybrid), Cowpea(Short), French Bean(Hybrid), French Bean(Rajma), Squash(Round), Mango(Dushari), Water Melon(Dotted), Papaya(Indian), Litchi(Indian), Cabbage, Potato Red(Mude), Tomato Big(Indian), Pear(Chinese), Tomato Small(Indian), Orange(Indian), Carrot(Terai), Tomato Small(Terai), Onion Dry (Chinese), Cabbage(Terai), Cauli Local(Jyapu), Pointed Gourd(Terai), Grapes(Black), Kiwi, Mango(Calcutte), Mango(Chousa)

Przykład 1. Oblicz Ile dni zostało do Sylwestra.

In [4]:
(pd.to_datetime('2026-12-31').date() - pd.to_datetime('today').date()).days # sprawdzane 21 października 2026r.

66

Przykład 2. Który miesiąc jest w dacie dla każdego wiersza danych?

In [5]:
df["Date"].dt.month_name("pl_PL.utf8") # po pozostałe przykłady odsyłam do wykładu nr 3 (powinien być na CEZ)

0         Czerwca
1         Czerwca
2         Czerwca
3         Czerwca
4         Czerwca
           ...
197156       Maja
197157       Maja
197158       Maja
197159       Maja
197160       Maja
Name: Date, Length: 197161, dtype: str

Przykład 3. Jakie rodzaje ziemniaków (_Potato_) są notowane w zbiorze danych?

In [6]:
df.loc[df["Commodity"].str.startswith("Potato"), "Commodity"].unique()

<StringArray>
['Potato Red', 'Potato White', 'Potato Red(Indian)', 'Potato Red(Mude)']
Length: 4, dtype: str

Przykład 4. Wskaż zmianę ceny kiwi od poprzedniego notowania

In [7]:
pd.DataFrame({"Data": df.loc[df["Commodity"]=="Kiwi", "Date"],
              "Cena": df.loc[df["Commodity"]=="Kiwi", "Average"],
              "Zmiana": df.loc[df["Commodity"]=="Kiwi", "Average"].diff(1)})

             Data   Cena  Zmiana
177541 2020-10-21  245.0     NaN
177623 2020-10-22  245.0     0.0
177701 2020-10-23  275.0    30.0
177780 2020-10-24  275.0     0.0
177847 2020-10-25  275.0     0.0
...           ...    ...     ...
195447 2021-04-24  425.0     0.0
195549 2021-04-25  425.0     0.0
195653 2021-04-26  550.0   125.0
195757 2021-04-27  550.0     0.0
195854 2021-04-28  550.0     0.0

[183 rows x 3 columns]

Przykład 5. Wskaż dla każdego produktu dzień, w którym odnotowano najniższą cenę i uzyskane wtedy ceny.

In [8]:

indx = df.groupby('Commodity')['Minimum'].idxmin()
df.loc[indx]

            SN            Commodity       Date Unit  Minimum  Maximum  Average
170087  170087          Apple(Fuji) 2020-07-04   KG    140.0    150.0    145.0
1680      1680        Apple(Jholey) 2013-07-17   Kg     50.0     60.0     55.0
27164    27164                 Arum 2014-09-28   Kg     10.0     12.0     11.0
24604    24604            Asparagus 2014-08-17   Kg     60.0     70.0     65.0
15971    15971               Bakula 2014-03-27   Kg     18.0     20.0     19.0
...        ...                  ...        ...  ...      ...      ...      ...
610        610               Turnip 2013-06-27   Kg     25.0     30.0     27.5
163660  163660             Turnip A 2020-03-17   Kg     20.0     25.0     22.5
141365  141365  Water Melon(Dotted) 2019-06-04   Kg     25.0     30.0     27.5
130232  130232   Water Melon(Green) 2018-12-16   Kg      1.0     55.0     28.0
31987    31987                  Yam 2014-12-16   Kg     18.0     22.0     20.0

[132 rows x 7 columns]

## Zadania

Wykorzystując poznane na zajęciach narzędzia

 1. Sprawdź ile dni zostało do początku najbliższej sesji egzaminacyjnej.
 1. Stwórz 4 kolumny z wartościami na podstawie kolumny daty:  dzień, miesiąc i rok z tej daty, jak również dzień tygodnia.
 1. Utwórz nową kolumnę w zbiorze danych kalimati, która będzie przechowywała liczbę dni jaka upłynęła od najniższej daty w danych.
 1. Wydobądź wszystkie pomidory (“Tomato”) z listy wszystkich produktów/dóbr zbioru danych kalimati (a jest tam kilka gatunków). (Warunek z wykorzystaniem odpowiedniej funkcji dla danych tekstowych)
 1. Odfiltruj informacje dla jedngo z dóbr nie będącego kiwi opisanego w zbiorze danych. W wynikowej ramce danych dodaj kolumnę ze zmianą ceny danego dnia od poprzedniego notowania.
 1. Na podstawie wyjściowego zbioru danych utwórz ramkę danych dla wszystkich gatunków pomidorów zawierającą kolumny (proszę zaproponować krótkie nazwy): 
   - nazwa produktu, 
   - data najniższego notowania (najniższej ceny), 
   - najniższa notowana cena, 
   - data notowania najwyższej ceny, 
   - najwyższa cena, 
   - pierwszy dzień notowania (data), 
   - ostatni dzień notowania (data),
   - średnia ceny ze wszystkich notowanych dni, 
   - liczba dni notowania danego produktu i
   - średnia cen ze wszystkich notowań w piątki.
  
  Wskazówka do ostatniego zadania: należy dokonać serii grupowań a następnie wyniki grupowań połączyć ze sobą metodą `merge` (vide wykład 2).

In [9]:
# 1. Sprawdź ile dni zostało do początku najbliższej sesji egzaminacyjnej.

(pd.to_datetime('2027-02-04').date() - pd.to_datetime('today').date()).days

101

In [10]:
# 2. Stwórz 4 kolumny z wartościami na podstawie kolumny daty:  dzień, miesiąc i rok z tej daty, jak również dzień tygodnia.

df["day"] = df["Date"].dt.day
df["month"] = df["Date"].dt.month
df["year"] = df["Date"].dt.year
df["day_of_week"] = df["Date"].dt.day_of_week

df

,SN,Commodity,Date,Unit,Minimum,Maximum,Average,day,month,year,day_of_week
0,0,Tomato Big(Nepali),2013-06-16,Kg,35.0,40.0,37.5,16,6,2013,6
1,1,Tomato Small(Local),2013-06-16,Kg,26.0,32.0,29.0,16,6,2013,6
2,2,Potato Red,2013-06-16,Kg,20.0,21.0,20.5,16,6,2013,6
3,3,Potato White,2013-06-16,Kg,15.0,16.0,15.5,16,6,2013,6
4,4,Onion Dry (Indian),2013-06-16,Kg,28.0,30.0,29.0,16,6,2013,6
...,...,...,...,...,...,...,...,...,...,...,...
197156,197156,Garlic Dry Nepali,2021-05-13,Kg,100.0,120.0,110.0,13,5,2021,3
197157,197157,Fish Fresh(Rahu),2021-05-13,KG,270.0,280.0,275.0,13,5,2021,3
197158,197158,Fish Fresh(Bachuwa),2021-05-13,KG,225.0,235.0,230.0,13,5,2021,3
197159,197159,Fish Fresh(Chhadi),2021-05-13,KG,220.0,230.0,225.0,13,5,2021,3
197160,197160,Fish Fresh(Mungari),2021-05-13,KG,240.0,250.0,245.0,13,5,2021,3

In [11]:
# 3. Utwórz nową kolumnę w zbiorze danych kalimati, która będzie przechowywała liczbę dni jaka upłynęła od najniższej daty w danych.

df["since_min_day"] = df["Date"] - df["Date"].min()
df

,SN,Commodity,Date,Unit,Minimum,Maximum,Average,day,month,year,day_of_week,since_min_day
0,0,Tomato Big(Nepali),2013-06-16,Kg,35.0,40.0,37.5,16,6,2013,6,0 days
1,1,Tomato Small(Local),2013-06-16,Kg,26.0,32.0,29.0,16,6,2013,6,0 days
2,2,Potato Red,2013-06-16,Kg,20.0,21.0,20.5,16,6,2013,6,0 days
3,3,Potato White,2013-06-16,Kg,15.0,16.0,15.5,16,6,2013,6,0 days
4,4,Onion Dry (Indian),2013-06-16,Kg,28.0,30.0,29.0,16,6,2013,6,0 days
...,...,...,...,...,...,...,...,...,...,...,...,...
197156,197156,Garlic Dry Nepali,2021-05-13,Kg,100.0,120.0,110.0,13,5,2021,3,2888 days
197157,197157,Fish Fresh(Rahu),2021-05-13,KG,270.0,280.0,275.0,13,5,2021,3,2888 days
197158,197158,Fish Fresh(Bachuwa),2021-05-13,KG,225.0,235.0,230.0,13,5,2021,3,2888 days
197159,197159,Fish Fresh(Chhadi),2021-05-13,KG,220.0,230.0,225.0,13,5,2021,3,2888 days
197160,197160,Fish Fresh(Mungari),2021-05-13,KG,240.0,250.0,245.0,13,5,2021,3,2888 days

In [14]:
# 4. Wydobądź wszystkie pomidory (“Tomato”) z listy wszystkich produktów/dóbr zbioru danych kalimati (a jest tam kilka gatunków). (Warunek z wykorzystaniem odpowiedniej funkcji dla danych tekstowych)

tomatos = df.loc[df["Commodity"].str.startswith("Tomato"), "Commodity"].unique()
tomatos

<StringArray>
[  'Tomato Big(Nepali)',  'Tomato Small(Local)', 'Tomato Small(Tunnel)',
   'Tomato Big(Indian)', 'Tomato Small(Indian)',  'Tomato Small(Terai)']
Length: 6, dtype: str

In [13]:
# 5. Odfiltruj informacje dla jedngo z dóbr nie będącego kiwi opisanego w zbiorze danych. W wynikowej ramce danych dodaj kolumnę ze zmianą ceny danego dnia od poprzedniego notowania.

df_pumpkin = df.loc[df["Commodity"] == "Pumpkin"]
df_pumpkin["average_diff"] = df.loc[df["Commodity"] == "Pumpkin", "Average"].diff(1)
#pd.set_option("display.max_rows", None)
df_pumpkin

,SN,Commodity,Date,Unit,Minimum,Maximum,Average,day,month,year,day_of_week,since_min_day,average_diff
22,22,Pumpkin,2013-06-16,Kg,18.0,20.0,19.0,16,6,2013,6,0 days,NaN
96,96,Pumpkin,2013-06-17,Kg,18.0,20.0,19.0,17,6,2013,0,1 days,0.0
168,168,Pumpkin,2013-06-18,Kg,18.0,20.0,19.0,18,6,2013,1,2 days,0.0
242,242,Pumpkin,2013-06-19,Kg,18.0,20.0,19.0,19,6,2013,2,3 days,0.0
315,315,Pumpkin,2013-06-20,Kg,18.0,20.0,19.0,20,6,2013,3,4 days,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
196735,196735,Pumpkin,2021-05-09,Kg,30.0,35.0,32.5,9,5,2021,6,2884 days,0.0
196828,196828,Pumpkin,2021-05-10,Kg,30.0,35.0,32.5,10,5,2021,0,2885 days,0.0
196918,196918,Pumpkin,2021-05-11,Kg,30.0,35.0,32.5,11,5,2021,1,2886 days,0.0
197010,197010,Pumpkin,2021-05-12,Kg,30.0,35.0,32.5,12,5,2021,2,2887 days,0.0
197100,197100,Pumpkin,2021-05-13,Kg,30.0,35.0,32.5,13,5,2021,3,2888 days,0.0

In [65]:
# 6. Na podstawie wyjściowego zbioru danych utwórz ramkę danych dla wszystkich gatunków pomidorów zawierającą kolumny (proszę zaproponować krótkie nazwy): 
#    - nazwa produktu, 
#    - data najniższego notowania (najniższej ceny), 
#    - najniższa notowana cena, 
#    - data notowania najwyższej ceny, 
#    - najwyższa cena, 
#    - pierwszy dzień notowania (data), 
#    - ostatni dzień notowania (data),
#    - średnia ceny ze wszystkich notowanych dni, 
#    - liczba dni notowania danego produktu i
#    - średnia cen ze wszystkich notowań w piątki.

df_tomatos = df.loc[df["Commodity"].str.startswith("Tomato")]

min_idx = df_tomatos.groupby("Commodity")["Minimum"].idxmin()
min_date = df_tomatos.loc[min_idx, ["Commodity", "Date", "Minimum"]]

max_idx = df_tomatos.groupby("Commodity")["Maximum"].idxmax()
max_date = df_tomatos.loc[max_idx, ["Commodity", "Date", "Maximum"]]

first_day_idx = df_tomatos.groupby("Commodity")["Date"].idxmin()
first_day = df_tomatos.loc[first_day_idx, ["Commodity", "Date"]]

last_day_idx = df_tomatos.groupby("Commodity")["Date"].idxmax()
last_day = df_tomatos.loc[last_day_idx, ["Commodity", "Date"]]

avg_alltime = df_tomatos.groupby("Commodity")["Average"].agg("mean")

df_tomatos_friday = df_tomatos.loc[df_tomatos["day_of_week"] == 4]
avg_friday = df_tomatos_friday.groupby("Commodity")["Average"].agg("mean")

df_merge = min_date.merge(max_date, on="Commodity", suffixes=("_min", "_max")).merge(first_day, on="Commodity").merge(last_day, on="Commodity").merge(avg_alltime, on="Commodity")
df_merge["num_of_days"] = df_merge["Date_y"] - df_merge["Date_x"]
df_merge = df_merge.merge(avg_friday, on="Commodity", suffixes=("_alltime", "_friday"))
df_merge

,Commodity,Date_min,Minimum,Date_max,Maximum,Date_x,Date_y,Average_alltime,num_of_days,Average_friday
0,Tomato Big(Indian),2021-05-02,25.0,2019-11-01,160.0,2019-06-25,2021-05-13,60.337553,688 days,60.362319
1,Tomato Big(Nepali),2014-05-07,14.0,2019-11-01,160.0,2013-06-16,2021-05-13,48.727962,2888 days,48.450685
2,Tomato Small(Indian),2021-02-21,10.0,2019-08-20,95.0,2019-08-08,2021-05-13,36.254902,644 days,35.057692
3,Tomato Small(Local),2021-02-20,8.0,2019-10-30,120.0,2013-06-16,2021-05-13,38.185516,2888 days,38.197500
4,Tomato Small(Terai),2021-02-21,10.0,2020-03-30,85.0,2019-12-06,2021-05-13,32.426573,524 days,31.500000
5,Tomato Small(Tunnel),2021-02-20,8.0,2019-10-30,120.0,2019-05-31,2021-05-13,44.833819,713 days,44.341837